apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: vote-app-dev
  name: vote-api-dev-configmap
data:
  application.yml: |- 
    server:
      port: 8081
      servlet:
        context-path: /VoteService

    vote:
      question: "這季NBA冠軍賽，你支持哪一隊呢？"
      options:
        - optionId: "01"
          label: "金塊"
          bgColor: "#000000"
        - optionId: "02"
          label: "熱火"
          bgColor: "#000000"
        - optionId: "03"
          label: "湖人"
          bgColor: "#000000"
        - optionId: "04"
          label: "勇士"
          bgColor: "#000000"

  logback-spring.xml: |- 
    <?xml version="1.0" encoding="UTF-8"?>
    <configuration>
      <springProperty scope="context" name="serverName" source="HOSTNAME" />
      <appender name="console" class="ch.qos.logback.core.ConsoleAppender">
        <encoder>
          <pattern>%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{sessionId}][%X{clientIp}][%X{token}][%X{companyUid}] %logger{10} line:%L - %msg%n</pattern>
          <charset>utf8</charset>
        </encoder>
      </appender>
      <root level="info">
        <appender-ref ref="console" />
      </root>
    </configuration>
